### ISSUE TITLE
Planeten Auswahl überarbeiten

### ISSUE THREAD

**Issue by jl0renzen** [jl0renzen/deepspacev-client-issues#18]
_From @M4lik on June 21, 2015 17:17_

Liste?

_Copied from original issue: jl0renzen/deepspacev-client#18_

**Comment by jl0renzen** [comment]
Wäre schön, wenn das Ganze als Option (bzw. Einstellung) eingebaut werden würde. Ich persönlich finde z.B. die grafische Übersicht hübscher, sehe aber, dass es sicherlich Leute gibt, die eine Liste aus Nutzbarkeitsgründen angenehmer finden.

**Comment by Z1egenPeter** [comment]
ich würde es auch gut finden wenn die auswahl auf dem aktuellen planeten bleiben würde bzw. irgendwo immer der planetenname steht aus übersichtsgründen
