### ISSUE TITLE
Lagerplatzanzeige überschreitet das Limit

### ISSUE THREAD

**Issue by jl0renzen** [jl0renzen/deepspacev-client-issues#20]
Wenn die Speicherkapazität aus verschiedenen und durchaus möglichen Gründen überschritten wird (z.B. heimkehrende Flotte mit Ressourcen), dann gleitet die Lagerplatzanzeige aus dem Rahmen:

![bug_storagebar](https://cloud.githubusercontent.com/assets/6105833/8337585/5b31eb8e-1aac-11e5-9fb5-724150132ddc.png)

**Comment by M4lik** [comment]
wollen wir den balken einfach nur begrenzen, oder eher verhindern, dass die ressourcen aufgenommen werden?

**Comment by jl0renzen** [comment]
Den Balken einfach bei 100% cappen. Wir können zwar für einige Aktionen zusätzlich unterbinden (z.B. eingehender Transport), aber nun mal nicht alle.
