### ISSUE TITLE
Gebäudebau-Trick

### ISSUE THREAD

**Issue by M4lik** [jl0renzen/deepspacev-client-issues#23]
Reproduzierbar:
1. Gebäude (mindestens stufe 1) abreißen lassen
2. Während der Auftrag ausgeführt wird eben dieses Gebäude Ausbauen
3. Abriss abrechen

-> Gebäude wird auf nächste Stufe ausgebaut (beispielsweise auf stufe 15), man bezahlt jedoch nur für die voherige Stufe (in diesem Fall 14).

**Comment by jl0renzen** [comment]
In diesem Fall würde ich - anstatt den Baupreis neu zu berechnen - einfach den Ausbau blocken während ein Abriss läuft. Schließlich macht dieser Vorgang, seitdem wir kein Ausbaulimit mehr haben, so oder so keinen Sinn.
